### ISSUE TITLE
missing reference

### ISSUE THREAD

**Issue by WildTact** [codemillmatt/xamarin-101#5]
**project**: xaml-navigation 
**file**: MainPage.xaml  
**error message**: missing assembly reference
`xmlns:local="clr-namespace:XAMLNav" `
may be 
`xmlns:local="clr-namespace:XAMLNav.ViewModels"`

**Comment by codemillmatt** [comment]
(sorry for the long delay)

`XAMLNav` should be the correct namespace in this case. However, if you're using Visual Studio - Windows and created the view model from file->new there ... then that'll give it that additional namespace and then the XAML import would throw that error. That's probably what's going on.
