### ISSUE TITLE
xaml-navigation : Navigation items not displaying for iOS 13.3

### ISSUE THREAD

**Issue by dave-l46** [codemillmatt/xamarin-101#6]
When debugging the XAMLNav or CodedUINav solution on an iOS 13.3 device (e.g. iPhone 7,8 11), the native nav items do not display.
Can you resolve please or advise why this is occurring ?

**Comment by brminnick** [comment]
Fixed: https://github.com/codemillmatt/xamarin-101/pull/7

iOS added a new API in iOS 13: https://github.com/xamarin/Xamarin.Forms/issues/7350#issuecomment-535905289
